### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by jb55** [TrimbleSolutionsCorporation/StructuresDeveloperKitExamples#1]
I'm relatively new to the tekla and the old xsteel apis. I'm doing some processing of large amounts of model data with realtime performance constraints, so I was interested in trying this out. Is this still supported? I couldn't find info about it anywhere, header files, etc.

**Comment by jmecosta** [comment]
hi,

yes, DevKit is released for each TS version as a native nuget package https://www.nuget.org/packages/StructuresDevKit/. The current sample exemplifies how you can create and build your application.

**Comment by jb55** [comment]
awesome! thanks.
