### ISSUE TITLE
Establishing RPC when application is launched?

### ISSUE THREAD

**Issue by jb55** [TrimbleSolutionsCorporation/StructuresDeveloperKitExamples#2]
Sorry if this is the wrong place to ask this...

I managed to get this working. In my case I'm looking to pull all of the model parts into a report. I need to do this for *many* models. I was looking into your headless example which uses the .NET apis, which seems to work ok.

I was looking into the native devkit because I want to do this as fast and efficiently as possible, but it appears these are a bit limited. I could only trigger the application via a macro and `command(one_point)`, it looks like Tekla only wants to open an RPC channel on it's own terms?

1. Is there any way to programatically launch these, or perhaps control when the application is launched?

2. Are calls via the RPC the only way this works, or are native plugins possible? 

3. Should I stick with the .NET apis for this purpose, perhaps as a plugin to avoid sending large amounts of data over RPC?

Thanks!

**Comment by jmecosta** [comment]
Hi,

cc @JukkaPartanen 

* Is there any way to programatically launch these, or perhaps control when the application is launched?  
  - no way, always established from Tekla Structures

* Are calls via the RPC the only way this works, or are native plugins possible?
  - only RPC supported

* Should I stick with the .NET apis for this purpose, perhaps as a plugin to avoid sending large amounts of data over RPC?
  - yes, .NET APIs recommended..

regards
